# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import manager_pb2 as manager__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/manager.ClientService/RegisterClient',
                request_serializer=manager__pb2.RegisterClientRequest.SerializeToString,
                response_deserializer=manager__pb2.Client.FromString,
                _registered_method=True)
        self.ConsultClient = channel.unary_unary(
                '/manager.ClientService/ConsultClient',
                request_serializer=manager__pb2.ConsultClientRequest.SerializeToString,
                response_deserializer=manager__pb2.Client.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=manager__pb2.RegisterClientRequest.FromString,
                    response_serializer=manager__pb2.Client.SerializeToString,
            ),
            'ConsultClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultClient,
                    request_deserializer=manager__pb2.ConsultClientRequest.FromString,
                    response_serializer=manager__pb2.Client.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manager.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manager.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.ClientService/RegisterClient',
            manager__pb2.RegisterClientRequest.SerializeToString,
            manager__pb2.Client.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.ClientService/ConsultClient',
            manager__pb2.ConsultClientRequest.SerializeToString,
            manager__pb2.Client.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TransactionServiceStub(object):
    """-------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTransaction = channel.unary_unary(
                '/manager.TransactionService/RequestTransaction',
                request_serializer=manager__pb2.PerformTransaction.SerializeToString,
                response_deserializer=manager__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.ConsultTransaction = channel.unary_stream(
                '/manager.TransactionService/ConsultTransaction',
                request_serializer=manager__pb2.ConsultClientRequest.SerializeToString,
                response_deserializer=manager__pb2.Transaction.FromString,
                _registered_method=True)


class TransactionServiceServicer(object):
    """-------------------------------------------------------

    """

    def RequestTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTransaction,
                    request_deserializer=manager__pb2.PerformTransaction.FromString,
                    response_serializer=manager__pb2.TransactionResponse.SerializeToString,
            ),
            'ConsultTransaction': grpc.unary_stream_rpc_method_handler(
                    servicer.ConsultTransaction,
                    request_deserializer=manager__pb2.ConsultClientRequest.FromString,
                    response_serializer=manager__pb2.Transaction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manager.TransactionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manager.TransactionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionService(object):
    """-------------------------------------------------------

    """

    @staticmethod
    def RequestTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manager.TransactionService/RequestTransaction',
            manager__pb2.PerformTransaction.SerializeToString,
            manager__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/manager.TransactionService/ConsultTransaction',
            manager__pb2.ConsultClientRequest.SerializeToString,
            manager__pb2.Transaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
