# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanager.proto\x12\x07manager\"I\n\x06\x43lient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x63redit_limit\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x01\";\n\x15RegisterClientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x63redit_limit\x18\x02 \x01(\x01\"\"\n\x14\x43onsultClientRequest\x12\n\n\x02id\x18\x01 \x01(\t\"Y\n\x12PerformTransaction\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"H\n\x13TransactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x01\"l\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x06 \x01(\t2\x93\x01\n\rClientService\x12\x41\n\x0eRegisterClient\x12\x1e.manager.RegisterClientRequest\x1a\x0f.manager.Client\x12?\n\rConsultClient\x12\x1d.manager.ConsultClientRequest\x1a\x0f.manager.Client2\xb2\x01\n\x12TransactionService\x12O\n\x12RequestTransaction\x12\x1b.manager.PerformTransaction\x1a\x1c.manager.TransactionResponse\x12K\n\x12\x43onsultTransaction\x12\x1d.manager.ConsultClientRequest\x1a\x14.manager.Transaction0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENT']._serialized_start=26
  _globals['_CLIENT']._serialized_end=99
  _globals['_REGISTERCLIENTREQUEST']._serialized_start=101
  _globals['_REGISTERCLIENTREQUEST']._serialized_end=160
  _globals['_CONSULTCLIENTREQUEST']._serialized_start=162
  _globals['_CONSULTCLIENTREQUEST']._serialized_end=196
  _globals['_PERFORMTRANSACTION']._serialized_start=198
  _globals['_PERFORMTRANSACTION']._serialized_end=287
  _globals['_TRANSACTIONRESPONSE']._serialized_start=289
  _globals['_TRANSACTIONRESPONSE']._serialized_end=361
  _globals['_TRANSACTION']._serialized_start=363
  _globals['_TRANSACTION']._serialized_end=471
  _globals['_CLIENTSERVICE']._serialized_start=474
  _globals['_CLIENTSERVICE']._serialized_end=621
  _globals['_TRANSACTIONSERVICE']._serialized_start=624
  _globals['_TRANSACTIONSERVICE']._serialized_end=802
# @@protoc_insertion_point(module_scope)
