{
 "title": "PSPD - Trabalho",
 "time": { "from": "2025-12-07T02:28:53.219Z", "to": "2025-12-07T03:15:57.357Z" },
 "panels": [
  {
   "title": "Máximo de requests/s (ClientService)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(rate(http_requests_total{handler=~\"/clients.*\"}[$__rate_interval]))[1d:])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Máximo de requests/s (TransactionService)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(rate(http_requests_total{handler=~\"/(transactions|extrato).*\"}[$__rate_interval]))[1d:])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Máximo de requests/s (Aplicação)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(rate(http_requests_total[$__rate_interval]))[1d:])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Tempo médio máximo por request (ClientService)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max(rate(http_request_duration_seconds_sum{handler=~\"/clients.*\"}[$__rate_interval])\n/\nrate(http_request_duration_seconds_count{handler=~\"/clients.*\"}[$__rate_interval]))[1d:])",
     "legendFormat": " {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Tempo médio máximo por request (TransactionsService)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max(rate(http_request_duration_seconds_sum{handler=~\"/(transactions|extrato).*\"}[$__rate_interval])\n/\nrate(http_request_duration_seconds_count{handler=~\"/(transactions|extrato).*\"}[$__rate_interval]))[1d:])",
     "legendFormat": " {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Tempo médio máximo por request (geral)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(max(rate(http_request_duration_seconds_sum[$__rate_interval])\n/\nrate(http_request_duration_seconds_count[$__rate_interval]))[1d:])",
     "legendFormat": " {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requisições sucesso e falha (ClientService)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "http_requests_total{handler=~\"/clients.*\", status=\"2xx\"}",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "http_requests_total{handler=~\"/clients.*\", status!=\"2xx\"}",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Requisições sucesso e falha (TransactionsService)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "http_requests_total{handler=~\"/(transactions|extrato).*\", status=\"2xx\"}",
     "legendFormat": "SUCCESS {{method}} {{handler}}"
    },
    {
     "expr": "sum(http_requests_total{handler=~\"/clients.*\", status!=\"2xx\"})",
     "legendFormat": "ERROR {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Tempo médio por requisição (ClientService)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=~\"/clients.*\"}[$__rate_interval])\n/\nrate(http_request_duration_seconds_count{handler=~\"/clients.*\"}[$__rate_interval])",
     "legendFormat": " {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Tempo médio por requisição (TransactionsService)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=~\"/(transactions|extrato).*\"}[$__rate_interval])\n/\nrate(http_request_duration_seconds_count{handler=~\"/(transactions|extrato).*\"}[$__rate_interval])",
     "legendFormat": " {{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests por segundo (ClientService)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (handler, method)(rate(http_requests_total{handler=~\"/clients.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests por segundo (ClientService)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (handler, method)(rate(http_requests_total{handler=~\"/(transactions|extrato).*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Tempo médio por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m])\n/\nrate(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests por segundo (geral)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (handler, method)(rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  }
 ]
}