import http from "k6/http";
import { check, sleep } from "k6";

export let options = {
  vus: __ENV.VUS ? parseInt(__ENV.VUS) : 50,
  duration: __ENV.DURATION || "30s",
};

export default function () {
  const url = __ENV.URL || "http://localhost:8000/api/process";
  const payload = JSON.stringify({
    client_id: null,
    name: `user-${Math.floor(Math.random()*100000)}`,
    value: Math.round(Math.random() * 1000) / 100.0,
    type: Math.random() > 0.5 ? "debit" : "credit",
    description: "generated by k6"
  });
  const params = { headers: { "Content-Type": "application/json" } };
  const res = http.post(url, payload, params);
  check(res, { "status 200": r => r.status === 200 });
  sleep(0.05);
}
